'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const {Store}=require('../store.cjs');const {tick,claim,begin,recover,result,manualReceipt,LEASE_MS}=require('../worker.cjs');
const {zonedLocal}=require('../domain.cjs');
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l3sAAAAASUVORK5CYII=','base64');
function setup(t,{mode='mock',latePolicy='pause'}={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tql-xhs-test-'));
 let now=Date.parse('2026-10-10T00:00:00Z');let s=new Store(dir,{clock:()=>now,allowMock:true});
 const a=s.account({label:'合成测试账号',mode}),asset=s.addAsset(PNG,'image/png');
 const p={title:'测试内容',body:'只用于隔离测试',topics:['FPL'],type:'image',accountId:a.id,images:[asset.id],cover:asset.id,video:null,source:'人工核验',isFpl:true,asOf:'2026-10-07T00:00:00Z',freshUntil:'2026-10-11T00:00:00Z',timezone:'Asia/Shanghai',localTime:'2026-10-10T09:00',expiresAt:'2026-10-10T12:00:00Z',latePolicy,graceSeconds:60};
 const c=s.save(p);t.after(()=>{try{s.close();}catch{}fs.rmSync(dir,{recursive:true,force:true});});
 return {get s(){return s;},dir,a,asset,p,c,setNow:t=>{now=typeof t==='string'?Date.parse(t):t;},advance:ms=>now+=ms,
 restart(){s.close();s=new Store(dir,{clock:()=>now,allowMock:true});},
 approve(){s.requestReview(c.id,s.current(c.id).version);const v=s.current(c.id);return s.approve(c.id,{version:v.version,hash:v.hash,accountId:v.payload.accountId,scheduledAt:v.payload.scheduledAt,acknowledged:true});},
 due(){now=Date.parse(p.localTime+'+08:00');},job(){return s.detail(c.id).jobs[0];}};
}
async function child(args){return new Promise((resolve,reject)=>{const p=spawn(process.execPath,args,{stdio:['ignore','pipe','pipe']});let err='';p.stderr.on('data',x=>err+=x);p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(Error(err||'child failed')));});}
test('正常排期：批准任务同事务，平台排期/审核/发布分别记录',async t=>{const f=setup(t);f.approve();assert.equal(f.job().state,'queued');assert.equal(f.s.get('SELECT count(*) n FROM xhs_approvals').n,1);f.due();await tick(f.s);assert.equal(f.job().state,'platform_scheduled');f.advance(31000);await tick(f.s);assert.equal(f.job().state,'reviewing');f.advance(31000);await tick(f.s);assert.equal(f.job().state,'published');assert.equal(f.job().receipt_kind,'mock');});
test('批准错误绑定拒绝，不留孤立批准或任务',t=>{const f=setup(t);f.s.requestReview(f.c.id,1);assert.throws(()=>f.s.approve(f.c.id,{version:1,hash:'old',accountId:f.a.id,scheduledAt:f.p.scheduledAt,acknowledged:true}),/APPROVAL_BINDING/);assert.equal(f.s.get('SELECT count(*) n FROM xhs_approvals').n,0);assert.equal(f.s.get('SELECT count(*) n FROM xhs_jobs').n,0);});
test('任务插入失败时批准记录回滚',t=>{const f=setup(t);f.s.db.exec("CREATE TRIGGER reject_job BEFORE INSERT ON xhs_jobs BEGIN SELECT RAISE(ABORT,'synthetic storage failure'); END");assert.throws(()=>f.approve(),/synthetic/);assert.equal(f.s.get('SELECT count(*) n FROM xhs_approvals').n,0);assert.equal(f.s.current(f.c.id).state,'pending');});
test('重启恢复：持久化排期无需网页存活',async t=>{const f=setup(t);f.approve();f.restart();f.due();await tick(f.s);assert.equal(f.job().state,'platform_scheduled');});
test('重复触发：同一批准只允许一条任务和一次提交',async t=>{const f=setup(t);f.approve();f.due();await Promise.all([tick(f.s),tick(f.s),tick(f.s)]);assert.equal(f.job().attempts,1);assert.equal(f.s.get('SELECT count(*) n FROM xhs_mock_receipts').n,1);assert.throws(()=>f.approve());});
test('真正多进程 worker 并发只提交一次',async t=>{const f=setup(t);f.approve();f.due();const code=`const {Store}=require(${JSON.stringify(path.resolve(__dirname,'../store.cjs'))});const {tick}=require(${JSON.stringify(path.resolve(__dirname,'../worker.cjs'))});const s=new Store(process.argv[1],{clock:()=>Date.parse('2026-10-10T01:00:00Z'),allowMock:true});tick(s).then(()=>s.close());`;await Promise.all(Array.from({length:5},()=>child(['-e',code,f.dir])));assert.equal(f.job().attempts,1);assert.equal(f.s.get('SELECT count(*) n FROM xhs_mock_receipts').n,1);});
test('提交意图后进程退出：恢复只核实，不重发',async t=>{const f=setup(t);f.approve();f.due();const code=`const {Store}=require(${JSON.stringify(path.resolve(__dirname,'../store.cjs'))});const {claim,begin}=require(${JSON.stringify(path.resolve(__dirname,'../worker.cjs'))});const s=new Store(process.argv[1],{clock:()=>Date.parse('2026-10-10T01:00:00Z'),allowMock:true});begin(s,claim(s));process.exit(0);`;await child(['-e',code,f.dir]);f.advance(LEASE_MS+1);let submitted=0,queried=0;await tick(f.s,{adapter:{submit:async()=>{submitted++;},query:async()=>{queried++;return {state:'unknown'};}}});assert.equal(submitted,0);assert.equal(queried,1);assert.equal(f.job().state,'unknown');});
test('提交前失去 worker 锁可安全恢复',async t=>{const f=setup(t);f.approve();f.due();claim(f.s);f.advance(LEASE_MS+1);await tick(f.s);assert.equal(f.job().attempts,1);});
test('批准后修改正文、账号或时间使旧批准失效，乐观锁防覆盖',t=>{const f=setup(t);f.approve();const old=f.job();const c=f.s.save({...f.p,title:'修改版本'},f.c.id,1);assert.equal(c.version,2);assert.equal(c.state,'draft');assert.equal(f.s.get('SELECT state FROM xhs_jobs WHERE id=?',old.id).state,'cancelled');assert.throws(()=>f.s.save(f.p,f.c.id,1),/STALE_VERSION/);assert.equal(f.s.all('SELECT * FROM xhs_versions').length,2);});
test('取消与提交同时发生：只能请求取消，平台确认后才完全取消',async t=>{const f=setup(t);f.approve();f.due();let release,entered;const started=new Promise(r=>entered=r);const promise=tick(f.s,{adapter:{submit:async()=>{entered();return new Promise(r=>release=r);}}});await started;f.s.cancel(f.c.id);assert.equal(f.job().state,'submitting');assert.equal(f.job().cancel_requested,1);release({state:'platform_scheduled',platformId:'mock-race',evidence:'mock'});await promise;assert.equal(f.job().state,'platform_scheduled');await tick(f.s);assert.equal(f.job().state,'cancelled');});
test('取消先完成则不提交',async t=>{const f=setup(t);f.approve();f.s.cancel(f.c.id);f.due();assert.equal(await tick(f.s),false);assert.equal(f.job().attempts,0);});
test('平台已排期后改期：先取消确认，再保存新版本重新批准',async t=>{const f=setup(t);f.approve();f.due();await tick(f.s);assert.throws(()=>f.s.save({...f.p,localTime:'2026-10-10T11:00'},f.c.id,1),/CANCEL_PLATFORM_FIRST/);f.s.cancel(f.c.id);await tick(f.s);assert.equal(f.job().state,'cancelled');f.s.save({...f.p,localTime:'2026-10-10T11:00'},f.c.id,1);f.approve();assert.equal(f.job().version,2);assert.equal(f.job().state,'queued');});
test('账号失效暂停，不能冒充服务器授权有效',async t=>{const f=setup(t);f.approve();f.s.account({id:f.a.id,label:f.a.label,mode:'mock',auth:'expired',revision:1});f.due();await tick(f.s);assert.equal(f.job().reason,'ACCOUNT_EXPIRED');assert.equal(f.job().attempts,0);});
test('结果不明和超时只进入查询，绝不直接重发',async t=>{const f=setup(t);f.approve();f.due();await tick(f.s,{adapter:{submit:()=>new Promise(()=>{})},timeoutMs:5});assert.equal(f.job().state,'unknown');f.advance(31000);let queries=0;await tick(f.s,{adapter:{query:async()=>{queries++;return {state:'unknown'};},submit:()=>assert.fail('must not submit')}});assert.equal(queries,1);assert.equal(f.job().attempts,1);});
test('过期锁 fencing 忽略旧 worker 回执',t=>{const f=setup(t);f.approve();f.due();const j=claim(f.s);begin(f.s,j);f.advance(LEASE_MS+1);recover(f.s);assert.equal(result(f.s,j,{state:'published',platformId:'mock-old',evidence:'mock'}),false);assert.equal(f.job().state,'unknown');});
test('只有明确未接收才有限重试，三次后停止',async t=>{const f=setup(t,{latePolicy:'within_window'});f.approve();f.due();const adapter={submit:async()=>({state:'retry',definitelyNotAccepted:true})};for(let i=0;i<3;i++){await tick(f.s,{adapter});f.advance(10000);}assert.equal(f.job().state,'failed');assert.equal(f.job().attempts,3);});
test('缺少 definitelyNotAccepted 的重试请求转待核实',async t=>{const f=setup(t);f.approve();f.due();await tick(f.s,{adapter:{submit:async()=>({state:'retry'})}});assert.equal(f.job().state,'unknown');});
test('素材删除或内容损坏会阻止提交',async t=>{const f=setup(t);f.approve();fs.unlinkSync(f.s.assetFile(f.asset.id));f.due();await tick(f.s);assert.equal(f.job().reason,'ASSET_MISSING');assert.equal(f.job().attempts,0);});
test('上传 MIME 不符、HTML、SVG、路径穿越拒绝',t=>{const f=setup(t);assert.throws(()=>f.s.addAsset(Buffer.from('<script>alert(1)</script>'),'image/png'),/MEDIA/);assert.throws(()=>f.s.addAsset(PNG,'image/svg+xml'),/MEDIA/);assert.throws(()=>f.s.assetFile('../../server.js'),/NOT_FOUND/);});
test('内容过期默认暂停，错过时间不擅自补发',async t=>{const f=setup(t);f.approve();f.setNow('2026-10-10T12:00:00Z');await tick(f.s);assert.equal(f.job().state,'expired');assert.equal(f.job().attempts,0);});
test('错过时间策略 pause 和 within_window 有区别',async t=>{const f=setup(t);f.approve();f.setNow('2026-10-10T01:02:00Z');await tick(f.s);assert.equal(f.job().reason,'MISSED_TIME_PAUSED');});
test('FPL 重要信息变化撤销未交付任务，不自动改写',async t=>{const f=setup(t);f.approve();const before=f.s.current(f.c.id).hash;f.s.flagChanged(f.c.id);f.due();await tick(f.s);assert.equal(f.job().reason,'SOURCE_CHANGED');assert.equal(f.s.current(f.c.id).hash,before);assert.equal(f.job().attempts,0);});
test('FPL 复核有效期失效时停止迟到补发',async t=>{const f=setup(t,{latePolicy:'within_window'});f.s.save({...f.p,freshUntil:'2026-10-10T01:01:00Z'},f.c.id,1);f.approve();f.setNow('2026-10-10T01:02:00Z');await tick(f.s);assert.equal(f.job().reason,'FPL_RECONFIRM_REQUIRED');});
test('时区转换支持北京/伦敦/半小时时区，DST gap/overlap 拒绝',()=>{assert.equal(zonedLocal('2026-10-10T09:00','Asia/Shanghai'),'2026-10-10T01:00:00.000Z');assert.equal(zonedLocal('2026-10-10T09:00','Europe/London'),'2026-10-10T08:00:00.000Z');assert.equal(zonedLocal('2026-10-10T09:00','Asia/Kolkata'),'2026-10-10T03:30:00.000Z');assert.throws(()=>zonedLocal('2026-03-29T01:30','Europe/London'),/NONEXISTENT/);assert.throws(()=>zonedLocal('2026-10-25T01:30','Europe/London'),/AMBIGUOUS/);assert.throws(()=>zonedLocal('2026-02-30T09:00','UTC'),/NONEXISTENT/);});
test('人工辅助不伪造平台发布；公开链接和编号核实后记录发布',async t=>{const f=setup(t,{mode:'manual'});f.approve();f.due();await tick(f.s);assert.equal(f.job().state,'manual_required');assert.equal(f.job().handed_at,null);manualReceipt(f.s,f.c.id,{jobId:f.job().id,version:1,acknowledged:true,state:'published',platformId:'testnote',noteUrl:'https://www.xiaohongshu.com/explore/testnote'});assert.equal(f.job().state,'published');assert.equal(f.job().receipt_kind,'manual');});
test('人工平台取消未确认不能显示已取消',async t=>{const f=setup(t,{mode:'manual'});f.approve();f.due();await tick(f.s);manualReceipt(f.s,f.c.id,{jobId:f.job().id,version:1,acknowledged:true,state:'platform_scheduled',platformId:'manual-note'});f.s.cancel(f.c.id);await tick(f.s);assert.equal(f.job().state,'unknown');assert.equal(f.job().cancel_requested,1);manualReceipt(f.s,f.c.id,{jobId:f.job().id,version:1,acknowledged:true,state:'cancelled',platformId:'manual-note'});assert.equal(f.job().state,'cancelled');});
test('凭据和未知账号字段拒绝；平台异常内容不进入日志/审计',async t=>{const f=setup(t);assert.throws(()=>f.s.account({label:'foo',cookie:'secret'}),/UNSUPPORTED/);f.approve();f.due();await tick(f.s,{adapter:{submit:async()=>{throw Error('Cookie: secret password=abc');}}});assert.equal(JSON.stringify(f.s.detail(f.c.id)).includes('secret'),false);});
test('伪造文件签名或截断容器拒绝',t=>{const f=setup(t);for(const [buf,mime] of [[Buffer.from([255,216,255,217]),'image/jpeg'],[Buffer.concat([PNG.subarray(0,20),Buffer.from('IEND')]),'image/png'],[Buffer.from('aaaaftypbbbbmoovccccmdat'),'video/mp4']])assert.throws(()=>f.s.addAsset(buf,mime),/DAMAGED/);});
test('素材字节修改后哈希不一致阻止提交',async t=>{const f=setup(t);f.approve();fs.appendFileSync(f.s.assetFile(f.asset.id),'changed');f.due();await tick(f.s);assert.equal(f.job().reason,'ASSET_CHANGED');});
test('人工辅助尚未交付时取消竞态可以本地确认取消',async t=>{const f=setup(t,{mode:'manual'});f.approve();f.due();const j=claim(f.s);begin(f.s,j);f.s.cancel(f.c.id);result(f.s,j,{state:'manual_required',reason:'MANUAL_HANDOFF_REQUIRED'});assert.equal(f.job().state,'cancelled');});
test('健康审核查询不因总查询次数耗尽而停止；不明结果有限核实',async t=>{const f=setup(t);f.approve();f.due();await tick(f.s);for(let i=0;i<8;i++){f.advance(31000);await tick(f.s,{adapter:{query:async()=>({state:'reviewing',platformId:'mock-review',evidence:'mock'})}});}assert.equal(f.job().query_failures,0);assert.equal(f.job().checks,8);for(let i=0;i<6;i++){f.advance(31000);await tick(f.s,{adapter:{query:async()=>({state:'unknown'})}});}assert.equal(f.job().query_failures,6);f.advance(31000);assert.equal(await tick(f.s),false);assert.equal(f.job().reason,'RECONCILIATION_LIMIT_MANUAL');});
test('重要信息变化时已交付平台的内容请求取消而非伪造暂停成功',async t=>{const f=setup(t);f.approve();f.due();await tick(f.s);f.s.flagChanged(f.c.id);assert.equal(f.job().state,'platform_scheduled');assert.equal(f.job().cancel_requested,1);await tick(f.s);assert.equal(f.job().state,'cancelled');});
test('已核实规则按账号配置且变更要求重新批准',async t=>{const f=setup(t);f.approve();f.s.rules={accountId:f.a.id,verified:true,digest:'new-rule-version',validUntil:'2027-01-01T00:00:00Z',image:{maxTitleCharacters:2}};f.due();await tick(f.s);assert.equal(f.job().reason,'PLATFORM_RULES_CHANGED');assert.throws(()=>f.s.save(f.p,f.c.id,1),/PLATFORM_TITLE_LIMIT/);});
test('备份可恢复且恢复任务隔离，避免重放旧排期',async t=>{const f=setup(t);f.approve();const dest=f.dir+'-backup';t.after(()=>fs.rmSync(dest,{recursive:true,force:true}));await child([path.resolve(__dirname,'../backup.cjs'),'--writers-stopped',f.dir,dest]);const restored=new Store(dest);assert.equal(restored.current(f.c.id).hash,f.c.hash);assert.equal(fs.readFileSync(restored.assetFile(f.asset.id)).equals(PNG),true);restored.close();await child([path.resolve(__dirname,'../quarantine-after-restore.cjs'),'--writers-stopped',dest]);const frozen=new Store(dest);assert.equal(frozen.active(f.c.id).state,'unknown');assert.equal(frozen.active(f.c.id).query_failures,6);assert.ok(frozen.active(f.c.id).handed_at);frozen.close();});
